{% set version = "2.0.19" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rxode2parse
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rxode2parse_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rxode2parse/rxode2parse_{{ version }}.tar.gz
  sha256: 9d418a353d226beb453a1112767fcc4da6196da843180e0a9581da8321640307

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'           # [win]
    - '*/tbb.dll'         # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh >=1.78.0.0
    - r-rcpp >=1.0.8
    - r-rcppeigen >=0.3.3.9.2
    - r-rcppparallel
    - r-stanheaders >=2.21.0.7
    - r-checkmate
    - r-crayon
    - r-data.table >=1.12.4
    - r-digest
    - r-dparser
    - r-knitr
    - r-qs
    - r-rex
    - r-symengine
  run:
    - r-base
    - {{ native }}gcc-libs           # [win]
    - {{ native }}libwinpthread-git  # [win]
    #- r-bh >=1.78.0.0
    - r-rcpp >=1.0.8
    - r-rcppeigen >=0.3.3.9.2
    - r-rcppparallel
    #- r-stanheaders >=2.21.0.7
    - r-checkmate
    - r-crayon
    - r-data.table >=1.12.4
    - r-digest
    - r-dparser
    - r-knitr
    - r-qs
    - r-rex
    - r-symengine

test:
  commands:
    - $R -e "library('rxode2parse')"           # [not win]
    - "\"%R%\" -e \"library('rxode2parse')\""  # [win]

about:
  home: https://nlmixr2.github.io/rxode2parse/
  dev_url: https://github.com/nlmixr2/rxode2parse/
  license: GPL-3.0-or-later
  summary: Provides the parsing needed for 'rxode2' (Wang, Hallow and James (2016) <doi:10.1002/psp4.12052>). It also provides the 'stan' based advan linear compartment model solutions with gradients (Carpenter et al (2015), <arXiv:1509.07164>) needed in 'nlmixr2' (Fidler et al (2019) <doi:10.1002/psp4.12445>). This split
    will reduce computational burden of recompiling 'rxode2'.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rxode2parse
# Title: Parsing and Code Generation Functions for 'rxode2'
# Version: 2.0.16
# Authors@R: c( person("Matthew L.", "Fidler", , "matthew.fidler@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-8538-6691")), person("Wenping", "Wang", , "wwang8198@gmail.com", role = "aut"), person("Richard", "Upton", role = "ctb"), person("Gabriel", "Staples", role="ctb"), person("Goro", "Fuji",  role="ctb", email="gfuji@cpan.org"), person("Morwenn","", role="ctb"), person("Igor", "Kushnir", role="ctb"), person("Kevin", "Ushey", role="ctb"), person("David", "Cooley", role="ctb"))
# Maintainer: Matthew L. Fidler <matthew.fidler@gmail.com>
# Description: Provides the parsing needed for 'rxode2' (Wang, Hallow and James (2016) <doi:10.1002/psp4.12052>). It also provides the 'stan' based advan linear compartment model solutions with gradients (Carpenter et al (2015), <arXiv:1509.07164>) needed in 'nlmixr2' (Fidler et al (2019) <doi:10.1002/psp4.12445>). This split will reduce computational burden of recompiling 'rxode2'.
# License: GPL (>= 3)
# URL: https://nlmixr2.github.io/rxode2parse/, https://github.com/nlmixr2/rxode2parse/
# BugReports: https://github.com/nlmixr2/rxode2parse/issues/
# Depends: R (>= 4.0.0)
# Imports: checkmate, crayon, dparser, knitr, methods, qs, Rcpp (>= 1.0.8), utils, digest, rex, data.table (>= 1.12.4)
# Suggests: testthat (>= 3.0.0), dplyr, nlmixr2data, devtools
# LinkingTo: BH (>= 1.78.0.0), dparser (>= 1.3.1-10), Rcpp (>= 1.0.8), RcppEigen (>= 0.3.3.9.2), StanHeaders (>= 2.21.0.7)
# Biarch: true
# Config/testthat/edition: 3
# Encoding: UTF-8
# Language: en-US
# NeedsCompilation: yes
# RoxygenNote: 7.2.3
# Packaged: 2023-03-28 13:16:54 UTC; matt
# Author: Matthew L. Fidler [aut, cre] (<https://orcid.org/0000-0001-8538-6691>), Wenping Wang [aut], Richard Upton [ctb], Gabriel Staples [ctb], Goro Fuji [ctb], Morwenn [ctb], Igor Kushnir [ctb], Kevin Ushey [ctb], David Cooley [ctb]
# Repository: CRAN
# Date/Publication: 2023-03-28 15:10:05 UTC
